export const GET_PRODUCTS= "GET_PRODUCTS";
export const GET_DETAIL = "GET_DETAIL";
export const GET_BY_NAME = "GET_BY_NAME";
export const ORDER_NAME = "ORDER_NAME";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const SET_FILTER = 'SET_FILTER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY'
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_FILTER_PRODUCTS = 'SET_FILTER_PRODUCTS';
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND';
export const SET_BRANDS = 'SET_BRANDS';
export const SEARCH_PRODUCTS_BY_NAME = 'SEARCH_PRODUCTS_BY_NAME';
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const RESET_FILTERS = 'RESET_FILTERS'
export const SET_NAME_ORDER = 'SET_NAME_ORDER';
export const SET_PRICE_ORDER = 'SET_PRICE_ORDER';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const GET_USERS = 'GET_USERS';


export const UPDATE_PRODUCT_STATUS = 'UPDATE_PRODUCT_STATUS';

export const REVIEW_SENT_SUCCESS = 'REVIEW_SENT_SUCCESS';
export const REVIEW_SENT_ERROR = 'REVIEW_SENT_ERROR';
export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_ERROR = 'UPDATE_REVIEW_ERROR';
export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
export const GET_ALL_REVIEW_USER = 'GET_ALL_REVIEW_USER';
export const ADMIN_REVIEW = 'ADMIN_REVIEW';
export const GET_PRODUCT_REVIEW = 'GET_PRODUCT_REVIEW';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';