export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const FILTER_BY_BRAND ="FILTER_BY_BRAND";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_BY_NAME = "GET_BY_NAME";
export const ORDER_PRODUCTS = "ORDER_NAME";
export const ORDER_PRICE = "ORDER_PRICE";

/* 
GET_ALL_PRODUCTS,
 GET_DETAIL_PRODUCT,
 GET_ALL_BRANDS,
 CLEAN_DETAIL,
 SEARCH_PRODUCTS,
 FILTER_BY_BRAND,
 FILTER_BY_CATEGORY,
 CREATE_PRODUCT,
 GET_BY_NAME,
 ORDER_PRODUCTS,
 ORDER_PRICE
 */