export const GET_POKEMONS = "GET_POKEMONS";
export const SEARCH_POKEMONS = "SEARCH_POKEMONS";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const GET_TYPES = "GET_TYPES";
export const GET_DETAIL = "GET_DETAIL";
export const GET_BY_NAME = "GET_BY_NAME";
export const FILTERDBAPI = "FILTERDBAPI";
export const FILTER_TYPE ="FILTER_TYPE";
export const ORDER_NAME = "ORDER_NAME";
export const ORDER_ATTACK = "ORDER_ATTACK";
export const CLEAN_DETAIL = "CLEAN_DETAIL";

/* 
GET_ALL_PRODUCTS,
 GET_DETAIL_PRODUCT,
 GET_ALL_BRANDS,
 CLEAN_DETAIL,
 SEARCH_PRODUCTS,
 FILTER_BY_BRAND,
 FILTER_BY_CATEGORY,
 CREATE_PRODUCT,
 GET_BY_NAME,
 ORDER_PRODUCTS,
 ORDER_PRICE
 */